### ISSUE TITLE
known bugs

### ISSUE THREAD

**Issue by Eric-szh** [agytw/stock-crawler#2] opened 2018-10-29 03:02 UTC
sometimes “connection is reset by peers”

**Comment by ghost** [comment] 2018-10-29 16:33
Possibly due to the Internet censorship in Mainland China, consider use SSL/TLS or proxy

**Comment by ghost** [comment] 2018-10-31 12:27
cannot replicate this issue outside Chinese network environment

seems it's not a bug, won't fix

**Closed as completed by ghost** 2018-10-31 12:27 UTC
Labels: wontfix
